/**
 * Migrates local media files to Cloudflare R2.
 *
 * Finds all media records in the DB where `prefix IS NULL` (uploaded before R2 was configured),
 * uploads original + size variants to R2, then sets `prefix = 'media'` in the DB so
 * Payload's s3Storage plugin starts serving them from R2.
 *
 * Run with: npm run migrate:r2
 * Requires: DATABASE_URI, S3_BUCKET, S3_ACCESS_KEY, S3_SECRET_KEY, S3_ENDPOINT, S3_PUBLIC_URL in .env.local
 */
'use strict'

const { Client } = require('pg')
const fs = require('fs')
const path = require('path')
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3')

const PUBLIC_MEDIA_DIR = path.resolve(__dirname, '../../public/media')

// Size variants generated by Payload (width x height from Media.ts imageSizes)
const SIZE_SUFFIXES = ['-400x300', '-768x512', '-1600x900']

function getMimeType(filename) {
  const ext = path.extname(filename).toLowerCase()
  const map = {
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.png': 'image/png',
    '.webp': 'image/webp',
    '.gif': 'image/gif',
  }
  return map[ext] || 'application/octet-stream'
}

async function uploadFile(s3, bucket, key, buffer, mimeType) {
  await s3.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: key,
      Body: buffer,
      ContentType: mimeType,
    })
  )
}

async function migrate() {
  const required = ['DATABASE_URI', 'S3_BUCKET', 'S3_ACCESS_KEY', 'S3_SECRET_KEY', 'S3_ENDPOINT', 'S3_PUBLIC_URL']
  const missing = required.filter((k) => !process.env[k])
  if (missing.length) {
    console.error('Missing env vars:', missing.join(', '))
    process.exit(1)
  }

  const s3 = new S3Client({
    endpoint: process.env.S3_ENDPOINT,
    region: process.env.S3_REGION || 'auto',
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY,
      secretAccessKey: process.env.S3_SECRET_KEY,
    },
    forcePathStyle: true,
  })

  const db = new Client({ connectionString: process.env.DATABASE_URI })
  await db.connect()

  try {
    const { rows } = await db.query(
      `SELECT id, filename, mime_type FROM media WHERE prefix IS NULL AND filename IS NOT NULL ORDER BY id`
    )

    console.log(`Found ${rows.length} local media records to migrate to R2\n`)

    let success = 0
    let skipped = 0
    let failed = 0

    for (const row of rows) {
      const { id, filename, mime_type } = row
      const localPath = path.join(PUBLIC_MEDIA_DIR, filename)

      if (!fs.existsSync(localPath)) {
        console.warn(`  ⚠  #${id} ${filename} — local file missing, skipping`)
        skipped++
        continue
      }

      process.stdout.write(`  ↑  #${id} ${filename} ... `)

      try {
        const mimeType = mime_type || getMimeType(filename)
        const ext = path.extname(filename)
        const base = path.basename(filename, ext)

        // Upload original
        const buffer = fs.readFileSync(localPath)
        await uploadFile(s3, process.env.S3_BUCKET, `media/${filename}`, buffer, mimeType)

        // Upload size variants that exist locally
        for (const suffix of SIZE_SUFFIXES) {
          const variantName = `${base}${suffix}${ext}`
          const variantPath = path.join(PUBLIC_MEDIA_DIR, variantName)
          if (fs.existsSync(variantPath)) {
            const variantBuffer = fs.readFileSync(variantPath)
            await uploadFile(s3, process.env.S3_BUCKET, `media/${variantName}`, variantBuffer, mimeType)
          }
        }

        // Mark as migrated: set prefix so s3Storage generates the correct public URL
        const publicUrl = `${process.env.S3_PUBLIC_URL}/media/${filename}`
        await db.query(
          `UPDATE media SET prefix = 'media', url = $1, updated_at = $2 WHERE id = $3`,
          [publicUrl, new Date().toISOString(), id]
        )

        console.log('✓')
        success++
      } catch (err) {
        console.error(`FAILED: ${err.message}`)
        failed++
      }
    }

    console.log(`\nDone!  ✓ ${success} migrated  ⚠ ${skipped} skipped  ✗ ${failed} failed`)
  } finally {
    await db.end()
  }
}

migrate().catch((err) => {
  console.error(err)
  process.exit(1)
})
